FROM python:3.9

WORKDIR /app

COPY . .

RUN pip install -r requirements.txt

COPY .env /app/.env

ENV TZ=EST5EDT
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN date

CMD ["python","-u","scripts/github-job.py"]
